### ISSUE TITLE
Image examples

### ISSUE THREAD

**Issue by dudung** [dudung/python#2]
# png with transparency
url https://www.pngwing.com/en/free-png-ykiil
![pngwing com](https://user-images.githubusercontent.com/7240685/227413693-5d05a8a8-00fc-470a-8a29-3167d7f27ed5.png)

**Comment by dudung** [comment]
# svg
url https://freesvg.org/veggie-leaf
![food-green-leaf](https://user-images.githubusercontent.com/7240685/227414751-8a525af1-6ef4-4cb4-902e-dfd0fe7cc170.svg)

**Comment by dudung** [comment]
# jpg
url https://www.pexels.com/photo/green-leafed-plant-2563742/
![pexels-kelly-2563742](https://user-images.githubusercontent.com/7240685/227415156-2ee4ce00-f88e-4ce6-9621-2b03b6d2f9cf.jpg)

**Comment by afinsani** [comment]
motor 
url https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Norton_Motorcycle.jpg/1200px-Norton_Motorcycle.jpg

![pemandangan jpg](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Norton_Motorcycle.jpg/1200px-Norton_Motorcycle.jpg)
