### ISSUE TITLE
Latihan 25 Maret 2023 -- markdown

### ISSUE THREAD

**Issue by dudung** [dudung/python#3]
Silakan mencoba contoh [markdown](https://github.com/dudung/python/blob/main/src/stepin/nonpython/markdown/README.md) yang diberikan dengan memberikan komentar di bawah ini.

Normal and **bold** and also __bold__
Normal and *Italic* and also _italic_

**Comment by aad169** [comment]
test1
---
testing 1.\
_testing 2_.\
~testing 3~.\
**end**.


test2
***
> quote 

1. Nol
    + Satu
    + Dua
      5. Tiga
   + Empat
      25. Lima
      26. Enam
5. Tujuh
    3. Delapan
    1. Sembilan
- Sepuluh
    + Sebelas
        5. Dua belas

test3
___
fungsi `hitung(angka1, angka2)` untuk menghitung jumlah angka 1 dan 2


test4
___
```sql
--testing dengan pewarnaan sql
select a.nama, b.nilai
from karyawan a 
left join grade b on a.nid = b.nid
```

test5
---
![logo itb jpg](https://www.itb.ac.id//themes/itbnew3/images/logo-itb-1920-new.png)

**Comment by inassuha** [comment]
Normal and **bold** and also __bold__

**Comment by dwy-prasat** [comment]
Normal and **Bold** and ~Coretan~

**Comment by veralaksa** [comment]
Latihan : 
**Nama :** Vera Elysa *Risti*
**Alamat :** Sukoharjo, ~Jawa Barat~ Jawa Tengah

**Comment by zains2itbdatascience** [comment]
> Data Diri Mahasiswa

Nama : **Zainuddin**
Jurusan : *Sains Data dan Pengelolaan Energi Listrik*
Universitas : ~univesitas~ Institut Teknologi Bandung

> Makanan Favorit

+ Bakso
  - Bakso Daging
    + Bakso Daging Sapi
    + Bakso Daging Ayam
  - Bakso Ikan
+ Nasi
  - Soto
    + Soto Ayam
    + Soto Babat
    + Soto Daging
  - Rawon
+ Minuman
  - Jus Jambu
  - Jus Mangga

**Comment by ghafuraws** [comment]
Normal
**tebal** dan  __bold__
*miring* dan _miring_
~salah~

**Comment by nilampuspita** [comment]
Hi, my Name is **Nilam**
From _UP3 Makassar Utara_
~Example~

You can find me on [GitHub](https://github.com/nilampuspita)

**Comment by RizkiNovitriPutri** [comment]
1. mulai 
 + 1 test \
 + 2 test \
+ 3 test \

*abc* **def** ~ghi~

**Comment by afinsani** [comment]
TULISAN NORMAL 
**TULISAN TEBAL**
_TULISAN MIRING_
_**TULISAN MIRING DAN TEBAL**_

**~AHMAD~** **AKHMAD** **FAEDA INSANI**

**Comment by zains2itbdatascience** [comment]
> Nama : **Zainuddin** Jurusan : _Sains Data dan Pengelolaan Energi Listrik_ Universitas : ~univesitas~ Institut Teknologi Bandung

**Comment by ghafuraws** [comment]
Google [Klik](http://www.google.com/)

**Comment by dwy-prasat** [comment]
My name is **Dwi Putra Prasatya**

You can find repositories on [GitHub](https://github.com/)
You can find me on [LinkedIn](www.linkedin.com/in)

**Comment by RizkiNovitriPutri** [comment]
```python
def add(x, y):
  z = x + y
  return z
```


abcdefghi
> sun is flower

![green leaf jpg](https://cdn.pixabay.com/photo/2019/12/29/23/11/sunflower-4728389_960_720.png)

**Comment by adityaadiaksa** [comment]
Normal and **bold** and also __bold__
Normal and *italic* and also _italic_
Normal and ~strikethrough~

tes

**Comment by ghafuraws** [comment]
1. Nol
    1. Satu
    1. Dua
        1. Tiga
    9. Empat
        1. Lima
        1. Enam
4. Tujuh
    1. Delapan
    1. Sembilan
       1. Sepuluh
1. Sebelas

**Comment by dwy-prasat** [comment]
![green leaf png](https://user-images.githubusercontent.com/7240685/227413693-5d05a8a8-00fc-470a-8a29-3167d7f27ed5.png)

**Comment by adityaadiaksa** [comment]
Kalimat 1.
Kalimat 2.
Kalimat 3.
Semua baris kata disini.

**Comment by adityaadiaksa** [comment]
1st sentence. 2nd sentence. 3rd setence. All sentences are in a paragraph.

**Comment by galiharisona** [comment]
**SK5003**
*Galih Arisona*


LATIHAN ~Dummy~

**Comment by aliefpascal** [comment]
# Latihan-Alief Pascal T Markdown

## Good Morning,
Hello everyone, my name is Alief Pascal. This is my first time writing a blog post, and I want to share how I learned to code in Python. Although I couldn't code before, my company urged me to learn it.

This is my diary of learning Python that I want to share with all of you. I hope you enjoy it.
### Here is my coding training schedule for next week:
Day | Activity
:-: | -:
Sunday |  Basic Syntax
Monday | Variables
Tuesday | Conditional
Wednesday | Function
Thursday | List 
Friday | tuples

### These are some *examples* of my coding:
```python
def add(x, y):
  z = x + y
  return z
```
And here are some references that may be helpful for you.
(https://roadmap.sh/python)
![green leaf jpg](https://user-images.githubusercontent.com/7240685/227415156-2ee4ce00-f88e-4ce6-9621-2b03b6d2f9cf.jpg)
Thank you!

**Comment by inassuha** [comment]
> Normal and **bold** and also **bold**



> Normal and **bold** and also **bold**

<p>
Inas
</p>

<p>Suha.</p>

<p>
Lailah</p>

<p>Each sentence is in each paragraph.
</p>

**Comment by titobagasw** [comment]
# Latihan Mark Down

## I. Huruf Tebal dan Miring
**tebal** juga __tebal__
*miring* juga _miring_
~strikethrough~

## II. Unordered List
+ 2023
    - Januari
        + Senin
            - Pagi
            - Siang
                + Hujan
            - Sore
                + Cerah
        + Selasa
    - Februari
+ 2024

## III. Ordered list
1. Satu
    1. Satu
        1. Aku
            Sayang ~__*maksimal*__ 4 tingkatan~
3. Ibu

## IV. Blockquote
Institut Teknologi Bandung
> Menggapai Martabat Bangsa dan Reputasi Dunia

## Tabel

:-: | :-: | :-: | :-: | :-: | :-:
Energy | Energy store | Renewable or non-renewable | Uses | Power output | Impact on environment
:- | :- | :- | :- | :- | :-
Fossil fuels (oil, coal and natural gases) | Chemical | Non-renewable | Transport, heating, electricity generation | High | Releases CO<sub>2</sub> (causes global warming)
Nuclear fuels | Nuclear | Non-renewable | Electricity generation | Very high | Radioactive waste (needs to be disposed of safely)
Biofuel | Chemical | Renewable | Transport, heating, electricity generation | Medium | Carbon-neutral so low impact
Wind | Kinetic | Renewable | Electricity generation | Very low | Take up large areas that could be used for farming, people say windmill spoil their view
Hydroelectricity | Gravitational potential | Renewable | Electricity  generation | Medium | Local habitats are affected by the large areas that need to be flooded to build dams
Geothermal | Internal | Renewable | Electricity generation, heating| Medium | Very low
Tides | Kinetic | Renewable | Electricity generation | Potentially very high but hard to harness | Tidal barrages can blocks sewage which needs to go out to sea
Sun | Nuclear | Renewable | Electricity generation | Potentially very high, but hard to harness | Very little
Water waves | Kinetic | Renewable | Electricity generation | Low | Very low

####### Bab 1.1.1.1.1 ~batas **maksimal** 6 subsection~

**Comment by Andinikma19** [comment]
# titleMenu | Jumlah | Harga
:-: | :- | -:
Nasi Goreng | 1 | 15k
Ayam Goreng | 1 | 30k
Soto | 1 | 25k
Ayam Geprek | 1 | 20k

**Comment by Andinikma19** [comment]
# Warung Barokah 

Menu | Harga | Tersedia/Habis
:-: | :- | -:
Ayam Goreng | 30k | Ada
Nasi Goreng | 15k | Ada
Ayam Geprek | 20k | Ada
Soto | 25k | Habis

**Comment by listynirmala** [comment]
1st sentence.
2nd sentence.
3rd setence.
All sentences are in a paragraph.

**Comment by listynirmala** [comment]
satu \
dua \
tiga \

**Comment by RizkiNovitriPutri** [comment]
Day | Hour | Condition
:-: | :- | -:
Sunday | 2.0 | Good
Monday | 2.5 | Medium
Tuesday | 0 | Bad
Wednesday | 1 | Not so bad
Thursday | 2 | Better
Friday | 4 | Good

**Comment by listynirmala** [comment]
+ Buku
  - Kamus
    + Bahasa
    + Teknis
  - Fiksi
  - Non-fiksi

**Comment by RizkiNovitriPutri** [comment]
Nama | Gambar
:-: | :- 
Bunga | ![green leaf png](https://a.wattpad.com/useravatar/yourbee10.256.943442.jpg)
Huruf | ![green leaf png](https://i.pinimg.com/474x/ea/d7/85/ead785f8a50100372e4dc3cecf21ef95.jpg)
Angka | ![green leaf png](https://belajaringgrisonline.com/computer1.png)

**Comment by RizkiNovitriPutri** [comment]
The equation is $y = ax^2 + bx + c$, where

$$\tag{1}
x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

are the roots.

**Comment by moestika** [comment]
# judul
Content
## sub judul
Content

**Comment by zuhrirachman** [comment]
**Monday**, then \
*Tuesday*, then \
*Wednesday*, then \
~Tuesday~, ups I mean \
*Thursday*, then \
*Friday*, then \
*Saturday*, and the last is \
**Sunday**

**Comment by RizkiNovitriPutri** [comment]
```mermaid
flowchart TB
  B --> I --> D
  D --Y--> O1a
  D --N--> O2a
  O1b --> P1 --> P3 --> O3a
  O2b --> P2 --> P3
  O3b --> O --> E
  B(("Mulai"))
  I[/"Input"/]
  D{"Decision"}
  O1a(("1"))
  O2a(("2"))
  O3a(("3"))
  O1b(("1"))
  O2b(("2"))
  O3b(("3"))
  P1["Process 1"]
  P2["Process 2"]
  P3["Process 3"]
  O[/"Output"/]
  E(("End"))
```

**Comment by SatrioYolandanu** [comment]
Coba Belajar Markdown
___

Day | Hour | Class
:-: | :- | -:
Senin | 3.0 | Sistem Hybrida Energi
Selasa | 2.0 | Numerik Lanjur
Rabu | 1 | Numerik Lanjut
Kamis | 2 | Algoritma Perangkat Lunak
Jum'at | 0 | Tidak Ada Kuliah
Sabtu | 2 | Pemrograman Dalam Sains

___

![Ari Yagami](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAhSiZs_ArBE8Qvqb9iPkf-UN4cM_Oay8nyZE7RApKZcLSaOEhuGqA9r-Eofw8GOHqrGY&usqp=CAU)

Nama : Satrio Yolandanu.

> Ada Ari aku yang lari.

**Comment by Yaksuwa** [comment]
```python
def add(x, y):
  z = x + y
  return z
```

**Comment by eidelbert** [comment]
# BAB 1
## BAB 1.1
### BAB 1.1.1
#### BAB 1.1.1.1
##### BAB 1.1.1.1
###### BAB 1.1.1.1.1

**Comment by afinsani** [comment]
Material| Density(g/cm<sup>3</sup>)| Material|Density(g/cm<sup>3</sup>)
:-: | :- | :-| -:
Alumunium | 2.64 | Iron(cast) | 7.21
Brass | 8.55 | Iron(wrough) |7.77
Coal(anthacite | 1.51 | Marble|2.56
Ice | 0.92 | Wood dry (red oak) | 0.70

**Comment by SatrioYolandanu** [comment]
| Energy | Energy store | Renewable or non-renewable | Uses | Power output | Impact on environment |
| --- | --- | --- | --- | --- | --- |
| Fossil fuels (oil, coal and natural gases) | Chemical | Non-renewable | Transport, heating, electricity generation | High | Releases CO2 (causes global warming) |
| Nuclear fuels | Nuclear | Non-renewable | Electricity generation | Very high | Radioactive waste (needs to be disposed of safely) |
| Biofuel | Chemical | Renewable | Transport, heating, electricity generation | Medium | Carbon-neutral so low impact |
| Wind | Kinetic | Renewable | Electricity generation | Very low | Take up large areas that could be used for farming, people say windmills spoil their view |
| Hydroelectricity | Gravitational potential | Renewable | Electricity generation | Medium | Local habitats are affected by the large areas that need to be flooded to build dams |
| Geothermal | Internal | Renewable | Electricity generation, heating | Medium | Very low |
| Tides | Kinetic | Renewable | Electricity generation | Potentially very high but hard to harness | Tidal barrages can block sewage which needs to go out to sea |
| Sun | Nuclear | Renewable | Electricity generation | Potentially very high, but hard to harness | Very little |
| Water waves | Kinetic | Renewable | Electricity generation | Low | Very low |
