### ISSUE TITLE
Latihan 25 Maret 2023 -- mathjax

### ISSUE THREAD

**Issue by dudung** [dudung/python#5]
Silakan mencoba contoh [mathjax](https://github.com/dudung/python/blob/main/src/stepin/nonpython/mathjax/README.md) yang diberikan dengan memberikan komentar di bawah ini.

**Comment by Yaksuwa** [comment]
Try
$x^2$ and $x_3$, and $x_3^5$ and $x^2_9$.

**Comment by antons1102** [comment]
The equation is $y = ax^2 + bx + c$, where

$$\tag{1}
x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

are the roots.

**Comment by inassuha** [comment]
The equation is $y = ax^2 + bx + c$, where

$$\tag{1}
x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

are the roots.

**Comment by dwy-prasat** [comment]
The equation is $y = ax^2 + bx + c$, where

$$\tag{1}
x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

are the roots.

**Comment by aliefpascal** [comment]
# Mathjax-Alief Pascal T 
## Try for write formula

$$
\sqrt{x + 2}
$$

$$
\sqrt[2]{x + 2}
$$

$\log x$ and not $log x$

**example of matrix 2x2**

$$
\left[
\begin{matrix}
11 & 12 \newline
21 & 22 \newline
\end{matrix}
\right]
$$

**Comment by zains2itbdatascience** [comment]
Cari solusi persamaan linear berikut :

$$\tag{1}
x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

Dikethui sistem persamaan seperti berikut :

$$\tag{2}
\frac{x + y + z}{a + b + c}
$$

Hitung nilai dari :

$$\tag{3}
\left[ \frac{1}{2} \right] + [ \frac{1}{2} ].
$$

Hitung nilai determinan dari matriks berikut :

$$
\left[
\begin{matrix}
11 & 12 & 13 & 14 \newline
21 & 22 & 23 & 24 \newline
31 & 32 & 33 & 34 \newline
\end{matrix}
\right]
$$

**Comment by ghafuraws** [comment]
$$
\sqrt{x + 4}
$$

$$
\sqrt[5]{x + 6}
$$

**Comment by listynirmala** [comment]
Equation $y=ax^2 + bx +c$, where

$$\tag{1}
x_{1,2}=\frac{-b \pm \sqrt{b^2 -4ac}}{2a}
$$

**Comment by aad169** [comment]
$$\tag{1}
c = \sqrt{{a^2 + b^2}}
$$

$\sin x$
$\cos x$

$(\frac{x}{y})$
$\left( \frac{x}{y} \right)$

$$
\left(
\begin{matrix}
1 & 0 & 0 \newline
0 & 1 & 0 \newline
0 & 0 & 1 \newline
\end{matrix}
\right)
$$

**Comment by antons1102** [comment]
They are $x^2$ and $x_3$, and $x_3^5$ and $x^2_9$.

**Comment by listynirmala** [comment]
Root

$$
\sqrt[3]{x+100}
$$

**Comment by antons1102** [comment]
An equation of

$$\tag{1}
\frac{x + y + z}{a + b + c}
$$


and the same equation of $\frac{x + y + z}{a + b + c}$.

**Comment by ghafuraws** [comment]
$$
\left(
\begin{matrix}
1 & 2 & 3 & 4 \newline
5 & 6 & 7 & 8 \newline
9 & 10 & 11 & 12 \newline
\end{matrix}
\right)
$$

**Comment by antons1102** [comment]
$$
\sqrt{x + 2}
$$

$$
\sqrt[5]{x + 2}
$$

**Comment by nilampuspita** [comment]
The equation is $y = ax^2 + bx + c$, where

$$\
x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

$$\tag{1}
\frac{x + y + z}{a + b + c}
$$

$$
\sqrt[5]{x + 2}
$$

It is $\sin x$ and not $cos x$.

$$
\left[
\begin{matrix}
-1 & 2 \newline
2 & -1 \newline
\end{matrix}
\right]
$$

They are $x^2$ and $x_3$, and $x_1^2$ and $x^2_5$.

$$
\left( \frac{1}{2} \right) +[ \frac{1}{2} ].
$$

$\log x$ and not $log x$

$$
\vec{r} = x \hat{i} +  y \hat{j} +  z \hat{k}
$$

$$
\bar{x} = \tfrac14 (x_1 + x_2 + x_3 + x_4)
$$

$$
s = \sum_{i = 1}^N u_i
$$

$$
i = \int_{a}^b f(x) dx
$$

$$
p = \prod_{j = 1}^M v_j
$$

**Comment by adityaadiaksa** [comment]
$$
\left[
\begin{matrix}
11 & 12 \newline
21 & 22 \newline
\end{matrix}
\right]
$$

$$
\left(
\begin{matrix}
11 & 12 & 13 & 14 \newline
21 & 22 & 23 & 24 \newline
31 & 32 & 33 & 34 \newline
\end{matrix}
\right)
$$

**Comment by ghafuraws** [comment]
$$
\left[ \frac{1}{2} \right] + [ \frac{1}{2} ]
$$

**Comment by antons1102** [comment]
$$
\left( \frac{1}{2} \right) + ( \frac{1}{2} ).
$$


$$
\left[ \frac{1}{2} \right] + [ \frac{1}{2} ].
$$

**Comment by galiharisona** [comment]
Formula gaji pegawai $Gaji = Kinerja^2 + Absensi$, 

$$\tag{1}
Absensi_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

tapi saya boong

**Comment by antons1102** [comment]
$$
\left[
\begin{matrix}
11 & 12 \newline
21 & 22 \newline
\end{matrix}
\right]
$$

$$
\left(
\begin{matrix}
11 & 12 & 13 & 14 \newline
21 & 22 & 23 & 24 \newline
31 & 32 & 33 & 34 \newline
\end{matrix}
\right)
$$

**Comment by listynirmala** [comment]
$sin x$ is wrong, it is $\sin x$ the same as $\cos x$ and $\tan x$

$$
\left [\frac{1}{4} \right] + [\frac{1}{4}]
$$

$$
\left(
\begin{matrix}
11 & 12 & 13 & 14 \newline
21 & 22 & 23 & 24 \newline
31 & 32 & 33 & 34 \newline
\end{matrix}
\right)
$$

**Comment by afinsani** [comment]
<h1>$$\lim_{x\to\infty}(\dfrac{1}{x})=0$$</h1>

**Comment by ghafuraws** [comment]
$$
\bar{x} = \tfrac14 (x_1^3 + x_2^2 + x_3 + 4)
$$

**Comment by antons1102** [comment]
$$
\vec{r} = x \hat{i} +  y \hat{j} +  z \hat{k}
$$

$$
\bar{x} = \tfrac14 (x_1 + x_2 + x_3 + x_4)
$$

**Comment by adityaadiaksa** [comment]
$$
\vec{r} = x \hat{i} +  y \hat{j} +  z \hat{k}
$$

$$
\bar{x} = \tfrac14 (x_1 + x_2 + x_3 + x_4)
$$

**Comment by inassuha** [comment]
$$
\sqrt {x + \sqrt{24}}
$$

**Comment by antons1102** [comment]
$$
s = \sum_{i = 1}^N u_i
$$

$$
i = \int_{a}^b f(x) dx
$$

$$
p = \prod_{j = 1}^M v_j
$$

**Comment by afinsani** [comment]
$$
\left(
\begin{matrix}
11 & 12 & 13 & 14 \newline
21 & 22 & 23 & 24 \newline
31 & 32 & 33 & 34 \newline
\end{matrix}
\right)
$$

**Comment by SatrioYolandanu** [comment]
It is $\sinh x$ and not $sinh x$.

\bar{x} = \tfrac14 (x_1 + x_2 + x_3 + x_4)
$$

$$
\left(
\begin{matrix}
11 & 12 & 13 & 14 \newline
21 & 22 & 23 & 24 \newline
31 & 32 & 33 & 34 \newline
\end{matrix}
\right)
$$

**Comment by veralaksa** [comment]
<h3> Mathjax</h3>
<h6> oleh : vera elysa </h6>

<h4>fraction </h4>
An equation of

$$\tag{1}
\frac{a + b + c}{d + e + f}
$$

and the same equation of $\frac{b + b + c}{d + e + f}$.

<h4>root</h4> <p>
$$
\sqrt[5]{x + 2}
$$
</p>

<h4> trigonometric_hyperbolic
</h4>

It is $\sin x$ and not $sin x$.

<h4> bracket </h4>

Large round brackets or parantheses

$$
\left( \frac{1}{2} \right) + ( \frac{1}{2} ).
$$

$$
\left[ \frac{1}{2} \right] + [ \frac{1}{2} ].
$$

<h4> matrix</h4>

$$
\left[
\begin{matrix}
112 & 121 \newline
211 & 221 \newline
\end{matrix}
\right]
$$

**Comment by Andinikma19** [comment]
## Soal 1
#### Soal 1 A
Tentukan nilai dari : $Ax^2$ = $Bx^2$, jika nilai a adalah 2

#### Soal 1 B
Berapakah nilai  $x$ pada $A_1$ $_1$ dari matriks diberikut ?

$$
\left[
\begin{matrix}
\left( \frac13x\right) & 1 \newline
21 & \left( \frac{6}{13} \right)  \newline
\end{matrix}
\right]
$$

## Soal 2

Tentukan nilai dari :

$$ 
\sqrt[ 3 ]{ a + 8 }
$$

**Comment by eidelbert** [comment]
$$
\left[
\begin{matrix}
\left[ \frac{1}{8} \right]  & 10 \newline
5 & \left[ \frac{1}{2} \right]  \newline
\end{matrix}
\right]
$$
